### ISSUE TITLE
Cannot create property 'skipBrokenMethodsCheck' on string 'BarBar'

### ISSUE THREAD

**Issue by lucasribeirop** [Claxl/StickerBot#5]
After scanning the QRCode this happens: TypeError: Cannot create property 'skipBrokenMethodsCheck' on string 'BarBar'

√ Authenticate to continue
√ WAPI Reinjected
√ Client is ready
TypeError: Cannot create property 'skipBrokenMethodsCheck' on string 'BarBar'
    at C:\Users\lucas\Desktop\bot\Teste\StickerBot-master\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:383:55
    at step (C:\Users\lucas\Desktop\bot\Teste\StickerBot-master\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:63:23)
    at Object.next (C:\Users\lucas\Desktop\bot\Teste\StickerBot-master\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:44:53)
    at fulfilled (C:\Users\lucas\Desktop\bot\Teste\StickerBot-master\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:35:58)

C:\Users\lucas\Desktop\bot\Teste\StickerBot-master>

**Comment by Claxl** [comment]
I'm working to upgrade it, because the API have been updated but the software not
